BryleIDP3-1/IDPFilo_Team_HW1

README.md
Added basic description and header placeholder text with different header sizes.
=> Add Placeholder Readme Text

README.md
=> Add Test Emoji Header

README.md
=> Change Emoji Header

README.md
=> Add Description Text

README.md
=> Add Emoji Test

README.md
Added Info on Categories and Emojis too.
=> Add Interest, Hobby, Goal Text

README.md
Added designing text to interest.
=> Add Text to Interest

README.md
Added links, more description, and portfolio division.
=> Add Portfolio

README.md
=> Change Text to Bold

README.md
Tested code for adding image to main.
=> Add Image Test

README.md
Added and adjusted photos and size.
=> Add Photo All

README.md
=> Reset Image Size

README.md
=> Add spacing test

README.md
=> Fix Space Test

README.md
=> Finalize and Add Text

README.md
=> Fix Spacing End

README.md
Added links to portfolio sites
=> Add Links to other sites

README.md
Added Text for Interesting Facts
=> Add Interesting Facts Section

README.md
=> Add Emoji Title

README.md
=> Add Emoji to Texts

README.md
=> Add Text to Facts Section

README.md
=> Fix Typo In Text

README.md
Added more description for texts
=> Expand the Description Texts

README.md
Edited some info and placement of emojis
=> Edit Text Info

README.md
Fixed error with checkmark for numbering
=> Fix Numbering Bullet

README.md
Added a link to my video portfolio
=> Add video Portfolio link

.gitignore
Added DS Store in the gitignore
=> Add gitignore DS Store

README.md
=> Remove 1 section

README.md
=> Adjust spacing and add emoji

README.md
Edited the code for images with photo name. Added some texts for the description and put MIT as license
=> Edit codes for images and edit descriptions

README.md
Added Emoji, Text to Credits, and Placed Alt Text
=> Add Emoji, Text to Credits, Place Alt Text
